services:
  - type: web
    name: bangla-sms-phishing-detector
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
